/**
     * @param { import('knex').Knex } knex
     */
    exports.seed = async function(knex) {
      await knex('usuario').del();
      await knex('usuario').insert([
  {
    "idUsuario": 1,
    "correo": "escuela1@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "2749892799",
    "nombre": "Escuela 1",
    "tipoPerfil": 1,
    "calle": "Avenida Durango 1250",
    "codigoPostal": "46688",
    "ciudad": "Arandas",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 2,
    "correo": "escuela2@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "9723758223",
    "nombre": "Escuela 2",
    "tipoPerfil": 1,
    "calle": "Boulevard Grecia 60",
    "codigoPostal": "47157",
    "ciudad": "Tlaquepaque",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 3,
    "correo": "escuela3@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "9003802806",
    "nombre": "Escuela 3",
    "tipoPerfil": 1,
    "calle": "Circunvalación Guinea 1678",
    "codigoPostal": "49420",
    "ciudad": "Guadalajara",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 4,
    "correo": "escuela4@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "4975486421",
    "nombre": "Escuela 4",
    "tipoPerfil": 1,
    "calle": "Callejón Moya 2178",
    "codigoPostal": "45003",
    "ciudad": "Arandas",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 5,
    "correo": "escuela5@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "4820395721",
    "nombre": "Escuela 5",
    "tipoPerfil": 1,
    "calle": "Callejón Norte Navarrete 10",
    "codigoPostal": "46658",
    "ciudad": "Tlaquepaque",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 6,
    "correo": "escuela6@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "2463671885",
    "nombre": "Escuela 6",
    "tipoPerfil": 1,
    "calle": "Viaducto Oaxaca 2130",
    "codigoPostal": "44254",
    "ciudad": "Autlán de Navarro",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 7,
    "correo": "escuela7@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "7696461569",
    "nombre": "Escuela 7",
    "tipoPerfil": 1,
    "calle": "Viaducto Sur Montes 387",
    "codigoPostal": "46234",
    "ciudad": "Tlaquepaque",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 8,
    "correo": "escuela8@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "5026589058",
    "nombre": "Escuela 8",
    "tipoPerfil": 1,
    "calle": "Calle Jalisco 674",
    "codigoPostal": "47829",
    "ciudad": "Puerto Vallarta",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 9,
    "correo": "aliado1@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "2155158496",
    "nombre": "Aliado 1",
    "tipoPerfil": 2,
    "calle": "Continuación Sur Villalpando 2149",
    "codigoPostal": "49912",
    "ciudad": "Ocotlán",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 10,
    "correo": "aliado2@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "4936899305",
    "nombre": "Aliado 2",
    "tipoPerfil": 2,
    "calle": "Calzada Sanches 2294",
    "codigoPostal": "45599",
    "ciudad": "Guadalajara",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 11,
    "correo": "aliado3@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "8451729871",
    "nombre": "Aliado 3",
    "tipoPerfil": 2,
    "calle": "Peatonal Norte Lucio 1983",
    "codigoPostal": "46872",
    "ciudad": "Guadalajara",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 12,
    "correo": "aliado4@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "4546183710",
    "nombre": "Aliado 4",
    "tipoPerfil": 2,
    "calle": "Circuito Rumania 511",
    "codigoPostal": "47953",
    "ciudad": "Tepatitlán de Morelos",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 13,
    "correo": "aliado5@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "9885700676",
    "nombre": "Aliado 5",
    "tipoPerfil": 2,
    "calle": "Pasaje Quintana Roo 1041",
    "codigoPostal": "48279",
    "ciudad": "Tlaquepaque",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 14,
    "correo": "aliado6@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "0261703958",
    "nombre": "Aliado 6",
    "tipoPerfil": 2,
    "calle": "Continuación Distrito Federal 2448",
    "codigoPostal": "48997",
    "ciudad": "Arandas",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 15,
    "correo": "aliado7@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "7352824671",
    "nombre": "Aliado 7",
    "tipoPerfil": 2,
    "calle": "Circunvalación Jordania 568",
    "codigoPostal": "45129",
    "ciudad": "Autlán de Navarro",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 16,
    "correo": "aliado8@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "7255670509",
    "nombre": "Aliado 8",
    "tipoPerfil": 2,
    "calle": "Callejón Tuvalu 1907",
    "codigoPostal": "48327",
    "ciudad": "Zapopan",
    "estado": "Jalisco"
  },
  {
    "idUsuario": 17,
    "correo": "admin@test.com",
    "contraseña": "12345",
    "estadoCuenta": true,
    "telefono": "7067353289",
    "nombre": "Administrador",
    "tipoPerfil": 3,
    "calle": "Avenida Ureña 1010",
    "codigoPostal": "45151",
    "ciudad": "Arandas",
    "estado": "Jalisco"
  }
]);
    };